[package]
name = "rocket-demo-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "lib"
path = "src/lib/mod.rs"

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["json", "uuid"]}